name: Docker Build

on:
  push:
		branches:
		- "master"

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: instapaper-to-evernote
